name: CI Actions
description: Greet someone and record the time
inputs:
  command:
    description: What utility command to run
    required: true
  vulnerabilities-file-path:
    description: Path to the Anchore reported vulnerabilities
  vulnerabilities-output-path: 
    description: File containing new vulnerabilities
    default: vulnerabilities_to_report.json
  github-token:
    description: Repo specific GitHub authentication token
runs:
  using: docker
  image: Dockerfile